/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core.views;

import core.DAO.ExerciseDAO;
import core.DAO.FavoriteDAO;
import core.DAO.IngredientDAO;
import core.DAO.PlateDAO;
import core.models.Exercise;
import core.models.Favorite;
import core.models.Ingredient;
import core.models.Plate;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import user.models.User;
import static user.views.UsersPerCountry.current_user;

/**
 *
 * @author Kevin
 */
public class addFavoriteGUI extends javax.swing.JFrame {
public static User current_user ;
    
/**
     * Creates new form addFavoriteGUI
     */
    public addFavoriteGUI(User user) {
        
        initComponents();
        current_user=user;
        ArrayList<Plate> plates = PlateDAO.findAll();
        DefaultComboBoxModel modelPlate = new DefaultComboBoxModel();
        
        for(Plate plate: plates){
            modelPlate.addElement(plate.getPlateName());
        }
        plateComboBox.setModel(modelPlate);
    
        ArrayList<Exercise> exercises = ExerciseDAO.findAll();
        DefaultComboBoxModel modelExercise = new DefaultComboBoxModel();
        for(Exercise exercise: exercises){
            modelExercise.addElement(exercise.getExerciseDescription());
        }
        ExerciseComboBox.setModel(modelExercise);
        
       
        ArrayList<Ingredient> ingredients = IngredientDAO.findAll();
        DefaultComboBoxModel modelIngredient = new DefaultComboBoxModel();
        for(Ingredient ingredient: ingredients){
            modelIngredient.addElement(ingredient.getName());
        }
        IngredientComboBox.setModel(modelIngredient);
        
        ArrayList<String> types;
        DefaultComboBoxModel modelTypes = new DefaultComboBoxModel();
        
            modelTypes.addElement("Desayuno");
            modelTypes.addElement("Almuerzo");
            modelTypes.addElement("Cena");
        TypeComboBox.setModel(modelTypes);
    
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ExerciseComboBox = new javax.swing.JComboBox<>();
        plateComboBox = new javax.swing.JComboBox<>();
        IngredientComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        TypeComboBox = new javax.swing.JComboBox<>();
        saveFavoriteButton = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Añade Tus Favoritos");

        jLabel2.setText("Ejercicio:");

        jLabel3.setText("Plato:");

        jLabel4.setText("Ingrediente:");

        ExerciseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        plateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        IngredientComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Tipo:");

        TypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        saveFavoriteButton.setText("Guardar");
        saveFavoriteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFavoriteButtonActionPerformed(evt);
            }
        });

        goBackButton.setText("Regresar");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ExerciseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IngredientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveFavoriteButton)
                            .addComponent(goBackButton))))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ExerciseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(plateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(IngredientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(saveFavoriteButton)
                .addGap(18, 18, 18)
                .addComponent(goBackButton)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveFavoriteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFavoriteButtonActionPerformed
       Favorite favorite = new Favorite();
        int id_favorite=1;
        
        java.sql.Date date = new java.sql.Date(Calendar.getInstance().getTime().getTime());
        int user_id =current_user.getId_user();
        
        Object itemIngredient = IngredientComboBox.getSelectedItem();
        
        String ingredientName = ((String)itemIngredient);
        Ingredient ingredient_D = IngredientDAO.find(ingredientName);
        int ingredient_id= ingredient_D.getId_ingredient();
        
        
        Object itemPlate = plateComboBox.getSelectedItem();
        String PlateName = ((String)itemPlate);
        Plate plate_D = PlateDAO.find(PlateName);
        int IDPlate = plate_D.getPlateID();
                
               
        Object itemExercise = ExerciseComboBox.getSelectedItem();
        String ExerciseName = ((String)itemExercise);
        Exercise exercise_D = ExerciseDAO.find(ExerciseName);
        int exercise_id = exercise_D.getExerciseID();
        
        Object item = TypeComboBox.getSelectedItem();
        String name = ((String)item);
        
        String type=name;
        
         
         favorite.setDate(date);
         favorite.setType(type);
         favorite.setUser_id(user_id);
         favorite.setIngredient_id(ingredient_id);
         favorite.setPlate_id(IDPlate);
         favorite.setExercise_id(exercise_id);
         favorite.setId_favorite(id_favorite);
               
         if (FavoriteDAO.create(favorite)>0){
                  this.setVisible(false);
        new HomeView(current_user).setVisible(true);
        }
    }//GEN-LAST:event_saveFavoriteButtonActionPerformed

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
         this.setVisible(false);
        new HomeView(current_user).setVisible(true);
    }//GEN-LAST:event_goBackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addFavoriteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addFavoriteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addFavoriteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addFavoriteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addFavoriteGUI(current_user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ExerciseComboBox;
    private javax.swing.JComboBox<String> IngredientComboBox;
    private javax.swing.JComboBox<String> TypeComboBox;
    private javax.swing.JButton goBackButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> plateComboBox;
    private javax.swing.JButton saveFavoriteButton;
    // End of variables declaration//GEN-END:variables
}
