/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core.views;

import admin.views.AdminHomeView;
import auth.views.BecomeCoachGUI;
import auth.views.LoginView;
import auth.views.TAC;
import auth.views.TACHome;
import auth.views.UserRegisterView;
import entrenador.views.SearchCoachView;
import entrenador.DAO.CoachDAO;
import entrenador.models.Coach;
import entrenador.views.MyUsersView;
import entrenador.views.ReceivedRequestsView;
import user.models.User;
import user.views.UserConfigView;
import core.views.consumption.*;
import java.sql.Date;
import core.DAO.ConsumptionDAO;
import core.models.Consumption;
import java.util.ArrayList;
import java.time.*;
import core.views.FavoriteView;
import core.views.ingredients.IngredientCatalogue;
import core.views.weight.WeightHome;
import user.views.SearchUsersView;
/**
 *
 * @author developer
 */
public class HomeView extends javax.swing.JFrame {
    /**
     * Creates new form HomeView
     */
    public static User current_user;
    
    public HomeView(User user) {
        initComponents();
        this.setLocationRelativeTo(null);
        current_user = user;
        System.out.println(current_user.getUsername());
        iduserLBL.setText(String.valueOf(user.getId_user()));
        usernameLabel.setText(user.getUsername());
        nameLabel.setText(user.getName());
        lastNameLabel.setText(user.getLast_name());
        descriptionLabel.setText(user.getDescription());
        
        
        
        if("Usuario".equals(current_user.getType())){
            // si el usuario no es entrenador puede buscar entrenadores pero no ver las solicitudes recibidas
           calificationLabel.setText("");
           rankLabel.setText("");
           becomeCoachButton.setVisible(true);
           searchCouchBtn.setVisible(true);
           searchUserBtn.setVisible(true);
           reporteBTN.setVisible(true);
           friendsBtn.setVisible(true);
           searchRecipesBtn.setVisible(true);
           
           receivedRequestsBtn.setVisible(false);
           user_coachBtn.setVisible(false);
        }else{
            Coach coach = CoachDAO.find(user.getId_user());        
            rankLabel.setText(String.valueOf(coach.getScore()));
            
            receivedRequestsBtn.setVisible(true);
            user_coachBtn.setVisible(true);
            
            searchCouchBtn.setVisible(false);
            searchUserBtn.setVisible(false);
            reporteBTN.setVisible(false);
            friendsBtn.setVisible(false);
            searchRecipesBtn.setVisible(false);
            becomeCoachButton.setVisible(false);
        }
        
        if("Admin".equals(current_user.getType())){
            adminBTN.setVisible(true);
        }else{
            adminBTN.setVisible(false);
        }
        
        int[] calo = calCalc();
        setCaloriesToConsume();
        setConsumedCalories();
    }

    public HomeView() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        rankLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        calificationLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        calories_to_consumeLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        consumed_caloriesLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        iduserLBL = new javax.swing.JLabel();
        btnConfigUsuario = new javax.swing.JButton();
        searchCouchBtn = new javax.swing.JButton();
        receivedRequestsBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        user_coachBtn = new javax.swing.JButton();
        searchUserBtn = new javax.swing.JButton();
        friendsBtn = new javax.swing.JButton();
        FavBtn = new javax.swing.JButton();
        searchRecipesBtn = new javax.swing.JButton();
        ingredientBTN = new javax.swing.JButton();
        weightBTN = new javax.swing.JButton();
        TACBTN = new javax.swing.JButton();
        adminBTN = new javax.swing.JButton();
        reporteBTN = new javax.swing.JButton();
        becomeCoachButton = new javax.swing.JButton();
        consumptionBTM = new javax.swing.JButton();
        toFavButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usernameLabel.setText("Nombre de Usuario");

        nameLabel.setText("Nombre");

        lastNameLabel.setText("Apellido");

        descriptionLabel.setText("Descripción");

        rankLabel.setText("Calificacion");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("User name:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Apellido:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Descripción");

        calificationLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        calificationLabel.setText("Calificación:");

        jLabel5.setText("Calorias a consumir:");

        calories_to_consumeLabel.setText("0");

        jLabel7.setText("Calorias consumidas:");

        consumed_caloriesLabel.setText("0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Codigo id de usuario:");

        iduserLBL.setText("ID");

        btnConfigUsuario.setText("Configuración Cuenta");
        btnConfigUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigUsuarioActionPerformed(evt);
            }
        });

        searchCouchBtn.setText("Buscador entrenador");
        searchCouchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCouchBtnActionPerformed(evt);
            }
        });

        receivedRequestsBtn.setText("Solicitudes recibidas");
        receivedRequestsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receivedRequestsBtnActionPerformed(evt);
            }
        });

        logOutBtn.setText("Cerrar Sesión");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        user_coachBtn.setText("Mis entrenados");
        user_coachBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_coachBtnActionPerformed(evt);
            }
        });

        searchUserBtn.setText("Buscador usuarios");
        searchUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchUserBtnActionPerformed(evt);
            }
        });

        friendsBtn.setText("Mis amigos");

        FavBtn.setText("Favoritos");
        FavBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavBtnActionPerformed(evt);
            }
        });

        searchRecipesBtn.setText("Buscador Recetas");
        searchRecipesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchRecipesBtnActionPerformed(evt);
            }
        });

        ingredientBTN.setText("Ingredientes");
        ingredientBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredientBTNActionPerformed(evt);
            }
        });

        weightBTN.setText("Peso");
        weightBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightBTNActionPerformed(evt);
            }
        });

        TACBTN.setText("Terminos y Condiciones");
        TACBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TACBTNActionPerformed(evt);
            }
        });

        adminBTN.setText("Panel Administrativo");
        adminBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBTNActionPerformed(evt);
            }
        });

        reporteBTN.setText("Reporte de consumos");
        reporteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteBTNActionPerformed(evt);
            }
        });

        becomeCoachButton.setText("Conviertete en entrenador");
        becomeCoachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                becomeCoachButtonActionPerformed(evt);
            }
        });

        consumptionBTM.setText("Mis Consumos");
        consumptionBTM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumptionBTMActionPerformed(evt);
            }
        });

        toFavButton.setText("Favoritos");
        toFavButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toFavButtonActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("FitByte Home");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(ingredientBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(weightBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator4)
                    .addComponent(TACBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consumptionBTM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(friendsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator6)
                    .addComponent(FavBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel8))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator7)
                                .addComponent(searchRecipesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchCouchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(toFavButton, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(calificationLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rankLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(nameLabel)
                                            .addComponent(usernameLabel)
                                            .addComponent(iduserLBL)
                                            .addComponent(lastNameLabel)
                                            .addComponent(descriptionLabel))
                                        .addGap(2, 2, 2))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(calories_to_consumeLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(consumed_caloriesLabel)))
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator9)
                        .addGap(10, 10, 10)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConfigUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator5)
                    .addComponent(adminBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reporteBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(receivedRequestsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator8)
                    .addComponent(becomeCoachButton, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(user_coachBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConfigUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reporteBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ingredientBTN))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(iduserLBL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(weightBTN)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(consumptionBTM)
                                        .addGap(13, 13, 13)
                                        .addComponent(friendsBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(FavBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(searchRecipesBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(searchUserBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(searchCouchBtn)
                                        .addGap(6, 6, 6)
                                        .addComponent(toFavButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(185, 185, 185)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(rankLabel)
                                            .addComponent(calificationLabel)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel1)
                                            .addComponent(usernameLabel))
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(nameLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(lastNameLabel))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(descriptionLabel))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(calories_to_consumeLabel))
                                        .addGap(9, 9, 9)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(consumed_caloriesLabel)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(TACBTN))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(receivedRequestsBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(becomeCoachButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(user_coachBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(200, 200, 200)
                                .addComponent(adminBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 15, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchCouchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCouchBtnActionPerformed
        this.dispose();
        SearchCoachView buscador = new SearchCoachView(current_user);
        buscador.setVisible(true);
    }//GEN-LAST:event_searchCouchBtnActionPerformed

    private void btnConfigUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigUsuarioActionPerformed
        // TODO add your handling code here:
        this.dispose();
        UserConfigView conf = new UserConfigView(current_user);
        conf.setVisible(true);
    }//GEN-LAST:event_btnConfigUsuarioActionPerformed

    private void receivedRequestsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receivedRequestsBtnActionPerformed
        this.dispose();
        ReceivedRequestsView received = new ReceivedRequestsView(current_user);
        received.setVisible(true);
    }//GEN-LAST:event_receivedRequestsBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        this.dispose();
        LoginView login = new LoginView();
        login.setVisible(true);
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void user_coachBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_coachBtnActionPerformed
        this.dispose();
        MyUsersView my_users = new MyUsersView(current_user);
        my_users.setVisible(true);    }//GEN-LAST:event_user_coachBtnActionPerformed

    private void ConsumptionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsumptionBtnActionPerformed
       
    }//GEN-LAST:event_ConsumptionBtnActionPerformed

    private void myFavBTMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myFavBTMActionPerformed
        FavoriteView fv = new FavoriteView(current_user);
        this.dispose();
        fv.setVisible(true);
    }//GEN-LAST:event_myFavBTMActionPerformed

    private void ingredientBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredientBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
        IngredientCatalogue catalogue = new IngredientCatalogue(current_user);
        catalogue.setVisible(true);
    }//GEN-LAST:event_ingredientBTNActionPerformed

    private void weightBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
        WeightHome weights = new WeightHome(current_user);
        weights.setVisible(true);
        
    }//GEN-LAST:event_weightBTNActionPerformed

    private void TACBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TACBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TACHome n = new TACHome(current_user);
        n.setVisible(true);
    }//GEN-LAST:event_TACBTNActionPerformed

    private void adminBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBTNActionPerformed
        // TODO add your handling code here:
            this.dispose();
            AdminHomeView  n = new AdminHomeView(current_user);
            n.setVisible(true);
        
    }//GEN-LAST:event_adminBTNActionPerformed

    private void reporteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteBTNActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Reports n = new Reports(current_user);
        n.setVisible(true);
    }//GEN-LAST:event_reporteBTNActionPerformed

    private void FavBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavBtnActionPerformed
        // TODO add your handling code here:
        FavoriteView fav = new FavoriteView(current_user);
        this.dispose();
        fav.setVisible(true);
    }//GEN-LAST:event_FavBtnActionPerformed

    private void becomeCoachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_becomeCoachButtonActionPerformed
        this.dispose();
        BecomeCoachGUI becomeCoach = new BecomeCoachGUI(current_user);
        becomeCoach.setVisible(true);
    }//GEN-LAST:event_becomeCoachButtonActionPerformed

    private void consumptionBTMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumptionBTMActionPerformed
        ConsumptionView cv = new ConsumptionView(current_user);
        this.dispose();
        cv.setVisible(true);
    }//GEN-LAST:event_consumptionBTMActionPerformed

    private void toFavButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toFavButtonActionPerformed
        addFavoriteGUI fav = new addFavoriteGUI(current_user);
        this.dispose();
        fav.setVisible(true);
    }//GEN-LAST:event_toFavButtonActionPerformed

    private void searchUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchUserBtnActionPerformed
        SearchUsersView friend = new SearchUsersView(current_user);
        this.dispose();
        friend.setVisible(true);
    }//GEN-LAST:event_searchUserBtnActionPerformed

    private void searchRecipesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchRecipesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchRecipesBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView(current_user).setVisible(true);
            }
        });
    }
    private int[] calCalc(){
        //Para hombres: (10 x peso de Kg) + (6,25 x altura en cm) – (5 x edad en años) + 5.
        int cons = (int) ((10*current_user.getWeight())+(6.25*current_user.getHeight())-(5*current_user.getAge())+5);
        int toCons = 0;
        Date td = new Date(System.currentTimeMillis());
        ArrayList<Consumption> selfCons = ConsumptionDAO.findAllID(current_user.getId_user());
        LocalDate ld = td.toLocalDate();
        DayOfWeek day = ld.getDayOfWeek();
        int d = day.getValue();
        String dia = "";
        switch(d){
            case(1): dia = "Lunes";
            case(2): dia = "Martes";
            case(3): dia = "Miercoles";
            case(4): dia = "Jueves";
            case(5): dia = "Viernes";
            case(6): dia = "Sabado";
            case(7): dia = "Domingo";
            default: dia = "";
        }
                
        for (Consumption c: selfCons){
            if (td.equals(c.getDate()) && current_user.getId_user() == c.getUser_id() && !c.isRec_coach()){
                cons = cons + c.getCalories();
            }
            if (dia.equals(c.getRec_day_weak()) && current_user.getId_user() == c.getUser_id() && c.isRec_coach()){
                toCons = toCons + c.getCalories();
            }
        }
        
        int[] ret = {cons, toCons - cons};
        return ret;
    }
    public void setCaloriesToConsume(){
        calories_to_consumeLabel.setText(calCalc()[0] + "");
    }
    public void setConsumedCalories(){
        consumed_caloriesLabel.setText(calCalc()[1] + "");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FavBtn;
    private javax.swing.JButton TACBTN;
    private javax.swing.JButton adminBTN;
    private javax.swing.JButton becomeCoachButton;
    private javax.swing.JButton btnConfigUsuario;
    private javax.swing.JLabel calificationLabel;
    private javax.swing.JLabel calories_to_consumeLabel;
    private javax.swing.JLabel consumed_caloriesLabel;
    private javax.swing.JButton consumptionBTM;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JButton friendsBtn;
    private javax.swing.JLabel iduserLBL;
    private javax.swing.JButton ingredientBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel rankLabel;
    private javax.swing.JButton receivedRequestsBtn;
    private javax.swing.JButton reporteBTN;
    private javax.swing.JButton searchCouchBtn;
    private javax.swing.JButton searchRecipesBtn;
    private javax.swing.JButton searchUserBtn;
    private javax.swing.JButton toFavButton;
    private javax.swing.JButton user_coachBtn;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JButton weightBTN;
    // End of variables declaration//GEN-END:variables
}
