/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core.views;

import core.DAO.MarcaDAO;
import core.models.Marca;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class marcaCreate extends javax.swing.JPanel {

    /**
     * Creates new form marcaCreate
     */
    public marcaCreate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        marcaNOMBRE_TF = new javax.swing.JTextField();
        marcaPAIS_TF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MC_okBT = new javax.swing.JButton();
        MC_exitBT = new javax.swing.JButton();
        LimpiarBT = new javax.swing.JButton();

        jLabel2.setText("Nombre de la marca");

        jLabel3.setText("Id del pais de la marca");

        MC_okBT.setText("Crear");
        MC_okBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MC_okBTActionPerformed(evt);
            }
        });

        MC_exitBT.setText("Salir");
        MC_exitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MC_exitBTActionPerformed(evt);
            }
        });

        LimpiarBT.setText("Limpiar");
        LimpiarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MC_exitBT, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(MC_okBT)
                        .addGap(18, 18, 18)
                        .addComponent(LimpiarBT)
                        .addGap(0, 68, Short.MAX_VALUE))
                    .addComponent(marcaNOMBRE_TF)
                    .addComponent(marcaPAIS_TF))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marcaNOMBRE_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marcaPAIS_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MC_exitBT)
                    .addComponent(MC_okBT)
                    .addComponent(LimpiarBT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MC_exitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MC_exitBTActionPerformed
        // TODO add your handling code here:
        hide();
    }//GEN-LAST:event_MC_exitBTActionPerformed

    private void MC_okBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MC_okBTActionPerformed
        // TODO add your handling code here:
        Marca registro = new Marca();
        registro.setNOMBRE(marcaNOMBRE_TF.getText());
        registro.setPAIS_ID(Integer.parseInt(marcaPAIS_TF.getText()));
        if(MarcaDAO.create(registro)>0){
            System.out.println("La marca fue añadida");
        }else{
            System.out.println("Hubo un error al añadir la marca");
        }
    }//GEN-LAST:event_MC_okBTActionPerformed

    private void LimpiarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarBTActionPerformed
        // TODO add your handling code here:
        marcaNOMBRE_TF.setText(null);
        marcaPAIS_TF.setText(null);
    }//GEN-LAST:event_LimpiarBTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LimpiarBT;
    private javax.swing.JButton MC_exitBT;
    private javax.swing.JButton MC_okBT;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField marcaNOMBRE_TF;
    private javax.swing.JTextField marcaPAIS_TF;
    // End of variables declaration//GEN-END:variables
}
