/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exercise.views;

import core.DAO.ExerciseDAO;
import core.models.Exercise;

/**
 *
 * @author Kevin
 */
public class exerciseAddGUI extends javax.swing.JPanel {

    /**
     * Creates new form exerciseAddGUI
     */
    public exerciseAddGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exerciseAddPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        exerciseIDTF = new javax.swing.JTextField();
        exerciseDescriptionTF = new javax.swing.JTextField();
        exerciseBurntTF = new javax.swing.JTextField();
        exerciseAddButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("Ingresa la ID de tu Ejercicio");

        jLabel3.setText("Añade una Descripcion");

        jLabel4.setText("Ingresa la cantidad de calorias quemadas cada hora");

        exerciseIDTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exerciseIDTFActionPerformed(evt);
            }
        });

        exerciseAddButton.setText("Añadir Ejercicio");
        exerciseAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exerciseAddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout exerciseAddPanelLayout = new javax.swing.GroupLayout(exerciseAddPanel);
        exerciseAddPanel.setLayout(exerciseAddPanelLayout);
        exerciseAddPanelLayout.setHorizontalGroup(
            exerciseAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exerciseAddPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(exerciseAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(exerciseAddPanelLayout.createSequentialGroup()
                        .addGroup(exerciseAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(101, 101, 101))
                    .addGroup(exerciseAddPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(exerciseAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exerciseDescriptionTF)
                    .addComponent(exerciseIDTF)
                    .addComponent(exerciseBurntTF)
                    .addComponent(exerciseAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addContainerGap())
        );
        exerciseAddPanelLayout.setVerticalGroup(
            exerciseAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exerciseAddPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(exerciseAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(exerciseIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(exerciseAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(exerciseDescriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(exerciseAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(exerciseBurntTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(exerciseAddButton)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jLabel1.setText("Añade tu Ejercicio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(exerciseAddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exerciseAddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void exerciseIDTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exerciseIDTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exerciseIDTFActionPerformed

    private void exerciseAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exerciseAddButtonActionPerformed
             Exercise exercise= new Exercise();
             int exerciseID=Integer.parseInt(exerciseIDTF.getText());
             String exerciseDescription=exerciseDescriptionTF.getText();
             int exerciseBurnt=Integer.parseInt(exerciseBurntTF.getText());
             exercise.setExerciseID(exerciseID);
             exercise.setExerciseDescription(exerciseDescription);
             exercise.setBurntHourCalorieExercise(exerciseBurnt);
             if (ExerciseDAO.create(exercise)>0){
               
               exerciseAddPanel.removeAll();
               exerciseAddPanel.revalidate();
               exerciseAddPanel.repaint();
               exerciseAddPanel.setVisible(true);
             }
             
    }//GEN-LAST:event_exerciseAddButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exerciseAddButton;
    private javax.swing.JPanel exerciseAddPanel;
    private javax.swing.JTextField exerciseBurntTF;
    private javax.swing.JTextField exerciseDescriptionTF;
    private javax.swing.JTextField exerciseIDTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
