/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core.views.consumption;

import core.DAO.ConsumptionDAO;
import core.DAO.ExerciseDAO;
import core.DAO.IngredientDAO;
import core.DAO.PlateDAO;
import core.DAO.User_CoachDAO;
import core.models.Consumption;
import core.models.User_Coach;
import entrenador.DAO.*;
import entrenador.models.*;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import user.DAO.UserDAO;
import user.models.User;

/**
 *
 * @author Diego
 */
public class CoachPane extends javax.swing.JPanel {
    private static User current_user = new User();
    DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form CoachPane
     */
    public CoachPane(User usuario) {
        current_user = usuario;
        initComponents();
        String s = "Seleccionar";
        DefaultComboBoxModel modelUser = new DefaultComboBoxModel();
        ArrayList<User_Coach> users = User_CoachDAO.findAll();
        ArrayList<Coach> cs = CoachDAO.findAll();
        Coach current_coach = new Coach();
        for (Coach c: cs){
            if (c.getId_user() == current_user.getId_user()){
                current_coach = c;
                break;
            }
        }
        modelUser.addElement(s);
        for(User_Coach u_c: users){
            if (u_c.getCouch_id() == current_coach.getId_coach()){
                System.out.println(u_c.getUser_id());
                User u = UserDAO.find(u_c.getUser_id());
                modelUser.addElement(u.getUsername());
            }
        }
        userCBX.setModel(modelUser);
        userCBX.setSelectedIndex(0);
        
        ArrayList<Object> columnas = new ArrayList<>();
        columnas.add("Ingrediente");
        columnas.add("Plato");
        columnas.add("Ejercicio");
        columnas.add("Calorias");
        columnas.add("Horas de Ejercicio");
        columnas.add("Dia de la semana");
        for (Object columna: columnas){
            model.addColumn(columna);
        }

    }
    
    public User userSelected(){
        String uSelected = (String)userCBX.getSelectedItem();
        User u = UserDAO.find(uSelected);
        return u;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coachPane = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        consumptionTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        userCBX = new javax.swing.JComboBox<>();
        selectBTM = new javax.swing.JButton();

        consumptionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ingrediente", "Plato", "Ejercicio", "Calorías", "Horas de Ejercicio", "Dia de la Semana"
            }
        ));
        jScrollPane4.setViewportView(consumptionTable);

        jLabel2.setText("Seleccione un usuario");

        userCBX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        selectBTM.setText("Seleccionar");
        selectBTM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBTMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout coachPaneLayout = new javax.swing.GroupLayout(coachPane);
        coachPane.setLayout(coachPaneLayout);
        coachPaneLayout.setHorizontalGroup(
            coachPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
            .addGroup(coachPaneLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(userCBX, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(selectBTM))
        );
        coachPaneLayout.setVerticalGroup(
            coachPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coachPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(coachPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectBTM))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(coachPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(coachPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectBTMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBTMActionPerformed
        ArrayList<Consumption> cons = ConsumptionDAO.findAll();
            ArrayList<Consumption> consumptions = new ArrayList<>();
            for (Consumption c: cons){
                if (c.getUser_id() == userSelected().getId_user()){
                    consumptions.add(c);
                }
            }
            for (Consumption c: consumptions){
                String ingredient = IngredientDAO.find(c.getIngredient_id()).getName();
                String plate = PlateDAO.find(c.getPlate_id()).getPlateName();
                String exercise = ExerciseDAO.find(c.getExercise_id()).getExerciseName();
                int calories = c.getCalories();
                int hExer = c.getNum_hours_excers();
                String weakDay = c.getRec_day_weak();
                Object[] data = new Object[]{ingredient, plate, exercise, calories, hExer, weakDay};
                model.addRow(data);
            }
            consumptionTable.setModel(model);
    }//GEN-LAST:event_selectBTMActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel coachPane;
    private javax.swing.JTable consumptionTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton selectBTM;
    private javax.swing.JComboBox<String> userCBX;
    // End of variables declaration//GEN-END:variables
}
